import type { ChallengeData } from './types'

/** 챌린지 목데이터. API 연동 시 이 파일만 교체하면 됨 */
export const INITIAL_CHALLENGES: ChallengeData[] = [
    {
        id: 'ramen',
        title: '서울 라멘 성지순례',
        emoji: '🍜',
        tag: '위치인증',
        dday: 'D-11',
        participants: 218,
        mine: '나 3/5',
        progress: 0.6,
        owner: '신재락현',
        joined: true,
        isCreator: true,
        target: 5,
        targetRestaurants: [
            { id: 'ramen-1', name: '홍대 라멘야', emoji: '🍜' },
            { id: 'ramen-2', name: '신림 분식', emoji: '🍜' },
            { id: 'ramen-3', name: '을지로 우동집', emoji: '🍲' },
            { id: 'ramen-4', name: '성수 라멘바', emoji: '🍜' },
            { id: 'ramen-5', name: '망원 라멘집', emoji: '🍜' },
        ],
        completedTargetIds: ['ramen-1', 'ramen-2', 'ramen-3'],
        rewardBadge: { emoji: '🍜', name: '라면 완주자', tone: 'bg-orange-100 text-orange-700' },
    },
    {
        id: 'naengmyeon',
        title: '평양냉면 성지순례',
        emoji: '🍲',
        tag: '위치인증',
        dday: 'D-3',
        participants: 176,
        mine: '나 1/3',
        progress: 1 / 3,
        owner: '윤하연수',
        joined: true,
        target: 3,
        targetRestaurants: [
            { id: 'naeng-1', name: '을지면옥', emoji: '🍲' },
            { id: 'naeng-2', name: '우래옥', emoji: '🥢' },
            { id: 'naeng-3', name: '필동면옥', emoji: '🍜' },
        ],
        completedTargetIds: ['naeng-1'],
        rewardBadge: { emoji: '🏅', name: '냉면 탐험가', tone: 'bg-amber-100 text-amber-700' },
    },
    {
        id: 'summer',
        title: '여름 별미 10선',
        emoji: '🍉',
        tag: '테마 수집',
        dday: 'D-18',
        participants: 93,
        mine: '나 1/4',
        progress: 0.25,
        owner: '신재락현',
        joined: true,
        isCreator: true,
        target: 4,
        targetRestaurants: [
            { id: 'summer-1', name: '성수 브런치', emoji: '🥞' },
            { id: 'summer-2', name: '망원 타코', emoji: '🌮' },
            { id: 'summer-3', name: '한남 스시', emoji: '🍣' },
            { id: 'summer-4', name: '연희 베이커리', emoji: '🥐' },
        ],
        completedTargetIds: ['summer-1'],
        rewardBadge: { emoji: '⭐', name: '여름 미식가', tone: 'bg-rose-100 text-rose-700' },
    },
    {
        id: 'gukbap',
        title: '국밥 로드',
        emoji: '🍲',
        tag: '완주',
        dday: '완료',
        participants: 132,
        owner: '민지수',
        completed: true,
    },
    {
        id: 'bakery',
        title: '동네 베이커리 투어',
        emoji: '🥐',
        tag: '테마 수집',
        dday: 'D-9',
        participants: 147,
        owner: '빵순이',
        joined: false,
    },
    {
        id: 'sushi',
        title: '주말 초밥 탐험대',
        emoji: '🍣',
        tag: '테마 수집',
        dday: 'D-6',
        participants: 119,
        owner: '스시러버',
        joined: false,
    },
    {
        id: 'spicy',
        title: '매운맛 정복하기',
        emoji: '🌶️',
        tag: '카운트',
        dday: 'D-14',
        participants: 81,
        owner: '매운콩',
        joined: false,
    },
]
